# Generated by Django 5.1.11 on 2025-06-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('temperature', models.FloatField(verbose_name='Temperatura')),
                ('humidity', models.FloatField(verbose_name='Humidade')),
                ('gas_value', models.IntegerField(verbose_name='Valor do gás')),
            ],
            options={
                'verbose_name': 'Leitura dos sensores',
                'verbose_name_plural': 'Leituras dos sensores',
                'ordering': ['-timestamp'],
            },
        ),
    ]
